patch-2
htcfreek/AutoIT-Scripts pull request #22
Opened 2021-07-04 17:16 UTC by Oleg-Chashko

Removed extra whitespace

2021-07-04 17:34 UTC, htcfreek commented
@Oleg-Chashko 
Is it possible that you fix #21 in your PR too? Thank you.

2021-07-04 17:37 UTC, htcfreek commented
@Oleg-Chashko 
Is it possible that you fix #21 in your PR too? Thank you.

2021-07-04 17:49 UTC, htcfreek requested changes

2021-07-04 17:49 UTC, htcfreek commented on src/GetDiskInfoFromWmi/GetDiskInfoFromWmi.au3
> + Title ...............: _GetDiskInfoFromWmi (GitHub https://github.com/htcfreek/AutoIt-Scripts)
```suggestion
 Title ...............: _GetDiskInfoFromWmi (GitHub: https://github.com/htcfreek/AutoIt-Scripts)
```

2021-07-04 18:04 UTC, Oleg-Chashko commented
Ready to merge?

2021-07-04 18:07 UTC, Oleg-Chashko commented
Please check, has everything been fixed already?

2021-07-05 14:01 UTC, closed without merging

2021-07-05 14:03 UTC, htcfreek commented
Why did you closed this?

2021-07-05 14:22 UTC, Oleg-Chashko commented
There was no merge, I deleted it when it was not needed.

2021-07-05 14:56 UTC, htcfreek commented
I only had not the time to look on it.